package com.sxj.mybatis01.mbg.model;

public class Girl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl.id
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl.age
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl.cup_size
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    private String cupSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl.id
     *
     * @return the value of girl.id
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl.id
     *
     * @param id the value for girl.id
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl.age
     *
     * @return the value of girl.age
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl.age
     *
     * @param age the value for girl.age
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl.cup_size
     *
     * @return the value of girl.cup_size
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    public String getCupSize() {
        return cupSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl.cup_size
     *
     * @param cupSize the value for girl.cup_size
     *
     * @mbggenerated Sat Oct 12 18:02:01 CST 2019
     */
    public void setCupSize(String cupSize) {
        this.cupSize = cupSize;
    }
}